### ISSUE TITLE
"a retention policy cannot be specified for asynchronous writes"

### ISSUE THREAD

**Issue by thom-nic** [influxdata/influxdb-ruby#140]
The README states
> a retention policy cannot be specified for asynchronous writes

Is this accurate?  Seems like a somewhat arbitrary limit and I'm not sure I understand why.

**Comment by dmke** [comment]
> Is this accurate?

Currently, yes.

The data points are enqueued in [`InfluxDB::Writer::Async#writer`](https://github.com/influxdata/influxdb-ruby/blob/0d5c2b2/lib/influxdb/writer/async.rb#L15) and later pushed to the server in [`InfluxDB::Writer::Async::Worker#check_background_queue`](https://github.com/influxdata/influxdb-ruby/blob/0d5c2b2/lib/influxdb/writer/async.rb#L111) (the `client.write` is defined in [`InfluxDB::Query::Core`](https://github.com/influxdata/influxdb-ruby/blob/0d5c2b2/lib/influxdb/query/core.rb#L57)). The problem here is, that given multiple points with different retention policies would require multiple HTTP-POST queries, as the retention policy is part of the request, not of the data points.

One could push a "job" instance (instead of only the data points) into the queue, i.e. points+RP, and group the data points by RP prior to HTTP-POST'ing to the server.

I'm not quite sure how that would affect the code readability (and performance) though, but I'm willing to accept a PR if the impact on performance is not too bad.

**Comment by thom-nic** [comment]
Does the async writer batch up multiple `write_point` calls?  Or does every `write_point` and `write_points` always result in a new POST from the async writer now?

**Comment by dmke** [comment]
Both `write_point` and `write_points` just call `write`, which does a HTTP-POST **on every invokaction** (this is one of the reasons, why you don't want to write each point separately but in a batch). The `Async` writer basically caches 1000 `write_point` calls before it sends them to the server.

**Comment by thom-nic** [comment]
Ok I see how it's working now.  Is the `precision` arg also ignored when using async?  It appears so from looking at https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/writer/async.rb#L15-L17

So assuming we start from the current state where `retention_policy`  (and `precision`?) should *never* be used with async, you could push a `[data, precision, rp]` sequences to the queue.  Then in `check_background_queue` one would pop/ batch sequential points so long as `precision` and `np` do not change.  Depending on usage patterns (again assuming the case where current state with async == "only use the default retention policy") you won't be much worse off performance-wise, save for the additional information that is enqueued with each item.  Which is to say, if you called `write_points` with 1000 metrics all for the same RP and precision, that would still get batched into a single HTTP call.  The only CPU performance penalty would be checking equality of the `precision` and `retention_policy` args to make sure they have not changed.

Another approach might be to do `data.join('\n')` after this line: https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/writer/async.rb#L16 before enqueueing it (along with precision and RP).  This would actually have potential to shrink the queue size if user is already taking advantage of `write_points` to batch data inserts.

Do either of those approaches seem acceptable?

**Comment by dmke** [comment]
> Is the `precision` arg also ignored when using async?

Yes, but I think that's less of a problem, since the default precision given to the `InfluxDB::Client` constructor is applied [here](https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/query/core.rb#L58).

> [...] push a `[data, precision, rp]` sequences to the queue [and] pop/ batch sequential points so long as `precision` and `rp` do not change

True, but once this feature exists, people will use it and shortly after we'll have a situation where sth. like this is is enqueued:

```ruby
[data, rp1, "s"],
[data, rp2, "ms"],
[data, rp3, "s"],
[data, rp1, "s"],
[data, rp2, "ms"],
# ...
```
i.e. every entry is different than the previous. A naive implementation would then only send individual points to the server.

> Another approach might be to do `data.join('\n')` [...] before enqueueing it (along with precision and RP). This would actually have potential to shrink the queue size

That has the disadvantage that we don't know the actual queue size. If I batch-write 500 and 900 data points, the queue would report to only hold 2 entries. The "job" sequence could hold a size attribute, and the [inner loop](https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/writer/async.rb#L102) in `Async#check_background_queue` could that take into account.

---

Again, if you want to take a shot at working on this, please do :-)

**Comment by dmke** [comment]
Closing this for now (feedback and PRs are still welcome!)

**Comment by vassilevsky** [comment]
Seems like #110 implements this.

**Comment by dmke** [comment]
No, the async writer ignores anything but the precision, see [ll. 15-18 in `InfluxDB::Writer::Async`](https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/writer/async.rb#L15-L18).

**Comment by vassilevsky** [comment]
@rockclimber73 is going to make a PR

**Comment by dmke** [comment]
Please do! :+1:
