### ISSUE TITLE
Does InfluxDB only run on Ruby 2+?

### ISSUE THREAD

**Issue by stevebissett** [influxdata/influxdb-ruby#151]
This has showed up in our CI package and it appears that only Ruby 2 is supported, but not mentioned as a requirement.

```
rake aborted!
SyntaxError: /home/ubuntu/<blank>/vendor/bundle/ruby/1.9.1/gems/influxdb-0.3.3/lib/influxdb/query/continuous_query.rb:13: syntax error, unexpected tLABEL
...atabase, query, resample_every: nil, resample_for: nil)
...                               ^
/home/ubuntu/<blank>/vendor/bundle/ruby/1.9.1/gems/influxdb-0.3.3/lib/influxdb/query/continuous_query.rb:13: Can't assign to nil
...se, query, resample_every: nil, resample_for: nil)
...                               ^
/home/ubuntu/<blank>/vendor/bundle/ruby/1.9.1/gems/influxdb-0.3.3/lib/influxdb/query/continuous_query.rb:31: syntax error, unexpected keyword_end, expecting $end
```

**Comment by dmke** [comment]
Yes, support for Ruby 2.0 was dropped in v0.2.0 of this gem. I've noticed though, that this isn't clearly communicated anywhere (except in the [commit message](https://github.com/influxdata/influxdb-ruby/commit/12dbb055f3988b21fa2063d1ae756d2f2306a3b1)):

> Refactor library (prepare to 0.9 support)
> - [...]
> - Break support for Ruby < 2
 
ref #150, #148 

---

How badly do you need support for Ruby 1.9? Since it looks like only `#create_continuous_query` relies on keyword arguments, I could refactor this as `options={}` argument (PRs welcome).

I'd prefer not to, though, but add a warning at the top of the README.

**Comment by dmke** [comment]
v0.3.4 is Ruby 1.9 compatible again and v0.3.3 is yanked from Rubygems.

I've also added a note in the README: I'll keep the 0.3.x releases compatible with Ruby 1.9, but expect this to change with v0.4.
