### ISSUE TITLE
background threads do not always exit

### ISSUE THREAD

**Issue by sethcall** [influxdata/influxdb-ruby#73]
If i shutdown influxdb server, and start rails, then sometimes the influxdb client worker threads won't ever shutdown. 

I believe this code is causing the issue:

```
at_exit do
            log :debug, "Thread exiting, flushing queue."
            check_background_queue(thread_num) until @queue.empty?
end
```

If there is something in the queue, it doesn't seem to exit it (I have to guess).  It could also be that there are other things running putting stuff back in the queue, while this 'last gasp' is being attempted.

If I take out this:
```
check_background_queue(thread_num) until @queue.empty?
```

Then I can always clean up nicely by hitting CTRL + C.

I understand why you would want to have the last_gasp behavior, but I think probably the best idea here is to only try and flush this queue for either a) a certain amount of time, or b) flush but give up if any attempts fail to reach influxdb server.

Or just don't do it at all... I'm OK with that, too.

**Comment by MisterFine1** [comment]
+1 on this issue.  I was about to deploy this into production, when I realized that if the gem is unable to send data to it's host, it will hang on exit.  I'd recommend the addition of a method to force a shutdown:

def shutdown!( max_delay = 20)

**Comment by thom-nic** [comment]
Hit this too, in CI (where there is no InfluxDB server) on my rails app `rspec` never exits because of this.  I will need to mock out the client or prevent any writes from being called, otherwise my CI tests will always hang.

**Comment by sethcall** [comment]
@thom-nic which version of the Influx-db are you using?

**Comment by thom-nic** [comment]
0.11.0.  Does this have anything to do with influx itself?  I'm deliberately not running an InfluxDB instance in CI.

**Comment by sethcall** [comment]
At one point, I had done this with an older version of Influxdb (this crashes in latest version of influxdb ruby client, though... there is no `@queue`)

```
module InfluxDB
  class Client
    def stop!
      @queue.clear if @queue
      @stopped = true
    end
  end
end
```

You have to have an instance of the client to call stop! on; I'm assuming you would in this case?

**Comment by dmke** [comment]
I will have a look at this issue when I'm home later. I've had a quick look yesterday (while doing some code cleaning), and I think I might know a solution to the problem...

**Comment by thom-nic** [comment]
@sethcall thanks for the tip.  After inspecting the client instance in a debugger I tried the following:
```ruby
module InfluxDB
  class Client
    def stop!
      puts "stopstopstopstopstopstopstopstopstopstopstopstop"
      if @config.async?
        @writer.worker.queue.clear
      end
      @stopped = true
    end
  end
end
```
however that still doesn't work.  It appears that `stop!` is never called.  Furthermore if I add my own `at_exit` hook it's never called.  

However if I add conditional logic such that `client.write_point` is never called during a test run then the exit hooks are called and everything exits cleanly.  Of course, if I never call `write_point` then there's nothing pending on the write queue and the `at_exit` hooks aren't needed!

That is still not a great solution however since the app will still hang in other scenarios, e.g. a legit network issue where the InfluxDB server can't be reached.

I'm not intimately familiar with ruby threading (moreso with Python/ Java threading) but according to [this SO topic](http://stackoverflow.com/questions/25579929/can-ruby-generate-non-daemonic-threads) a spawned thread shouldn't prevent the process from exiting unless it's explicitly being waited on from the main thread...?

**Comment by dmke** [comment]
@thom-nic I've adjusted the code a bit, would you mind checking against the `bugfix/73` branch, i.e. by adding this to your Gemfile and running your specs again?

```ruby
gem "influxdb", github: "influxdata/influxdb-ruby", branch: "bugfix/73"
```

If your test still fails, would you prepare a (minimal) demo app for me to reproduce your error?

**Comment by thom-nic** [comment]
@dmke yup - I removed my monkey patch (which upon further inspection looks like it may have been discarding queued messages under non-exit conditions!) and my latest CI tests are passing as well as locally.  Thanks for the quick fix!

**Comment by dmke** [comment]
Cool. I have merged the commit into master and released v0.2.5.

**Comment by toddboom** [comment]
Thanks for crushing this one, @dmke!

**Comment by thom-nic** [comment]
Yes, thank you!
